services:
  mysql:
    volumes:
      - ~/Documents/projects/volumes/mysql-saas:/var/lib/mysql
    image: mysql:8.0
    container_name: mysql-saas
    command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 3310:3306
