version: '3.8'

services:
  mysql:
    volumes:
      - ~/Documents/projects/volumes/mysql-saas:/var/lib/mysql
    image: mysql
    container_name: mysql-saas
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 3307:3306
